# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170830_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y-%m-%d'),
        ),
    ]
