# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170901_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user',), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_status',
            field=models.CharField(choices=[('schoolboy', 'Школьник'), ('student', 'Студент'), ('working', 'Рабочий'), ('сivil_servant', 'Госслужащий'), ('businessman', 'Предприниматель'), ('unemployed', 'Безработный'), ('other', 'Другое')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('blocked', 'Заблокирован'), ('activated', 'Активный'), ('waits for activation', 'Ожидает активацию')], default='waits for activation', max_length=50),
        ),
    ]
