# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170901_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name',), 'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
    ]
